name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # สร้างเฉพาะตอนที่ยังไม่มีโฟลเดอร์ android เพื่อป้องกันติด v1 และไม่ลบไฟล์ที่คุณแต่งทิ้ง
      - name: Generate Android if not exists
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-v2
          path: build/app/outputs/flutter-apk/app-release.apk
